name: Lint project
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # perform matrix testing to give us an earlier insight into issues with different versions of supported major versions of Go
      matrix:
        # strategy is used to allow us to pin to a specific Go version, or use the version available in our `go.mod`
        strategy: ['go-version']
        version: [1.21]
        include:
          # pick up the Go version from the `go.mod`
          - strategy: 'go-version-file'
            version: 'go.mod'
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          ${{ matrix.strategy }}: ${{ matrix.version }}

      - name: Run `make lint-ci`
        run: make lint-ci
